spring.application.name=controle

# ==========================================
# Configuração Dinâmica de Banco (H2 Local por padrão, Postgres na nuvem)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/controle_estoque;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_PLATFORM:org.hibernate.dialect.H2Dialect}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Configurações do SQL Server Local (Comentadas para uso futuro se desejar)
# ==========================================
# spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=EstoqueMaster;encrypt=true;trustServerCertificate=true;
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.datasource.username=ANAJULIA\\SQLEXPRESS
# spring.datasource.password=Aj#2026_Sql!Dev$91
# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
